# Introdução ao Python para Data Science - Ramo Estudantil IEEE UFPB

Este notebook é uma introdução ao uso de Python para Data Science. Vamos cobrir conceitos básicos de Python e introduzir bibliotecas populares usadas em Data Science, como NumPy, Pandas, Matplotlib e Scikit-learn. Cópie o notebook, execute e finalize.

## Sumário
1. [Introdução ao Python](#section1)
2. [NumPy: Arrays e Operações Matemáticas](#section2)
3. [Pandas: Manipulação de Dados](#section3)
4. [Matplotlib: Visualização de Dados](#section4)
5. [Scikit-learn: Introdução ao Machine Learning](#section5)
5. [Extra - opcional](#section6)

<a name="section1"></a>
## 1. Introdução ao Python

### 1.1 Variáveis e Tipos de Dados

É possível de ver valores com tipagens diferentes

In [37]:
# Declarando variáveis
a = 10       # Inteiro
b = 20.5     # Float
c = "Hello, Python!"  # String
d = True     # Booleano

print("a:", a, " - Tipo:", type(a))
print("b:", b, " - Tipo:", type(b))
print("c:", c, " - Tipo:", type(c))
print("d:", d, " - Tipo:", type(d))


a: 10  - Tipo: <class 'int'>
b: 20.5  - Tipo: <class 'float'>
c: Hello, Python!  - Tipo: <class 'str'>
d: True  - Tipo: <class 'bool'>


### 1.2 Estruturas de Dados: tipagem

In [38]:
# Lista
lista = [1, 2, 3, 4, 5]
print("Lista:", lista)

# Tupla
tupla = (1, 2, 3, 4, 5)
print("Tupla:", tupla)

# Dicionário
dicionario = {"nome": "Ana", "idade": 23, "cidade": "São Paulo"}
print("Dicionário:", dicionario)

# Conjunto
conjunto = {1, 2, 3, 4, 5}
print("Conjunto:", conjunto)


Lista: [1, 2, 3, 4, 5]
Tupla: (1, 2, 3, 4, 5)
Dicionário: {'nome': 'Ana', 'idade': 23, 'cidade': 'São Paulo'}
Conjunto: {1, 2, 3, 4, 5}


### 1.3 Estruturas de Controle

In [39]:
a = 10
b = 9

# Condicional
if a < b:
    print("a é menor que b")
else:
    print("a é maior ou igual a b")

# Laço de repetição
for i in range(5):
    print("Valor de i:", i)

# Loop while
contador = 0
while contador < 5:
    print("Contador:", contador)
    contador += 1


a é maior ou igual a b
Valor de i: 0
Valor de i: 1
Valor de i: 2
Valor de i: 3
Valor de i: 4
Contador: 0
Contador: 1
Contador: 2
Contador: 3
Contador: 4


### 1.4 Funções

In [40]:
# Definindo uma função
def soma(x, y):
    return x + y

resultado = soma(5, 3)
print("Soma:", resultado)

# Função com argumento padrão
def saudacao(nome="Mundo"):
    print(f"Olá, {nome}!")

saudacao("Ana")
saudacao()


Soma: 8
Olá, Ana!
Olá, Mundo!


### Desafio 1: Implementação de Estruturas de Dados em Python
**Problema**

Você foi contratado para implementar uma versão simplificada de uma lista encadeada (LinkedList) em Python. Sua tarefa é criar uma classe para a lista encadeada e adicionar métodos para inserir, remover e buscar elementos.

Requisitos

1. **Classe Node:**

Deve representar um nó na lista encadeada.
Deve conter um valor (data) e um ponteiro para o próximo nó (next).

2. **Classe LinkedList:**

Deve representar a lista encadeada.
Deve ter um ponteiro para o nó inicial (head).
Métodos a serem implementados:
insert(value): Insere um novo nó com o valor especificado no final da lista.
remove(value): Remove o nó com o valor especificado da lista.
search(value): Retorna True se o valor estiver presente na lista, caso contrário, False.
display(): Exibe todos os valores na lista encadeada.


--> Exemplo de lista encadeada em C: [link](https://www.ime.usp.br/~pf/algoritmos/aulas/lista.html)

--> Exemplo de lista encadeada em python: [link](https://awari.com.br/lista-encadeada-em-python-aprenda-a-estrutura-de-dados-essencial-para-programacao/?utm_source=blog&utm_campaign=projeto+blog&utm_medium=Lista%20Encadeada%20em%20Python:%20Aprenda%20a%20Estrutura%20de%20Dados%20Essencial%20para%20Programa%C3%A7%C3%A3o#:~:text=As%20listas%20encadeadas%20em%20Python,que%20ser%C3%A3o%20armazenados%20na%20lista.)


In [41]:
# Definindo a classe Node
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# Definindo a classe LinkedList
class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, value):
        new_node = Node(value)
        if self.head == None:
            self.head = new_node
        else:
            current_node = self.head
            while current_node.next:
                current_node = current_node.next
            current_node.next = new_node
    
    def display(self):
        current_node = self.head
        while current_node:
            print(f"{current_node.data} -> ", end="")
            current_node = current_node.next
        print("None")
    
    def search(self, value):
        current_node = self.head
        while current_node.next:
            if current_node.data == value:
                return True
            current_node = current_node.next
        return False

    def remove(self, value):
        current_node = self.head
        while current_node.next:
            if current_node.next.data == value:
                current_node.next = current_node.next.next
                break
            current_node = current_node.next


# Exemplo de uso
ll = LinkedList() # Instanciando a classe

ll.insert(1) #chamando o método da classe
ll.insert(2)
ll.insert(3)
ll.display()  # Output: 1 -> 2 -> 3 -> None

print(ll.search(2))  # Output: True

ll.remove(2)
ll.display()  # Output: 1 -> 3 -> None
print(ll.search(2))  # Output: False


1 -> 2 -> 3 -> None
True
1 -> 3 -> None
False


## Desafio 2 - Implementação de Estrutura de Dados: Pilha

Neste desafio, você irá implementar a estrutura de dados de uma pilha (stack) em Python. A pilha é uma estrutura de dados que segue o princípio LIFO (Last In, First Out), onde o último elemento adicionado é o primeiro a ser removido.

## Tarefas

1. **Implementar a Classe `Stack`**:
    - A classe `Stack` deve conter os seguintes métodos:
        - `__init__`: Inicializa a pilha.
        - `push(item)`: Adiciona um item no topo da pilha.
        - `pop()`: Remove e retorna o item do topo da pilha.
        - `peek()`: Retorna o item do topo da pilha sem removê-lo.
        - `is_empty()`: Retorna `True` se a pilha estiver vazia, caso contrário, `False`.
        - `size()`: Retorna o número de elementos na pilha.

2. **Testar a Classe `Stack`**:
    - Crie uma instância da pilha e realize operações de push, pop, peek, e verificação de vazio.
    - Verifique se o tamanho da pilha está correto após várias operações.

In [42]:
# Preencha o código abaixo para completar cada tarefa.

class Stack:
    def __init__(self):
       self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if self.is_empty():
            return None
        return self.items.pop()

    def peek(self):
        if self.is_empty():
            return None
        return self.items[-1]

    def is_empty(self):
        return self.size() == 0

    def size(self):
        return len(self.items)


In [43]:
# Testando a classe Stack

if __name__ == "__main__":
    stack = Stack()

    # Testando push
    stack.push(1)
    stack.push(2)
    stack.push(3)
    print("Pilha após push de 1, 2, 3:", stack.items)

    # Testando pop
    print("Item retirado do topo:", stack.pop())
    print("Pilha após pop:", stack.items)

    # Testando peek
    print("Item no topo da pilha:", stack.peek())

    # Testando is_empty
    print("A pilha está vazia?", stack.is_empty())

    # Testando size
    print("Tamanho da pilha:", stack.size())

    # Removendo todos os itens e testando operações em pilha vazia
    stack.pop()
    stack.pop()
    print("A pilha está vazia após remover todos os itens?", stack.is_empty())
    print("Tentativa de retirar item da pilha vazia:", stack.pop())
    print("Tentativa de ver o item do topo da pilha vazia:", stack.peek())

Pilha após push de 1, 2, 3: [1, 2, 3]
Item retirado do topo: 3
Pilha após pop: [1, 2]
Item no topo da pilha: 2
A pilha está vazia? False
Tamanho da pilha: 2
A pilha está vazia após remover todos os itens? True
Tentativa de retirar item da pilha vazia: None
Tentativa de ver o item do topo da pilha vazia: None


<a name="section2"></a>
## 2. NumPy: Arrays e Operações Matemáticas

NumPy é uma biblioteca fundamental para computação científica em Python. Ela oferece suporte para arrays multidimensionais e matrizes, além de uma coleção de funções matemáticas para operar esses arrays.

### 2.1 Criando Arrays

In [44]:
import numpy as np

In [45]:
# Criando arrays unidimensionais
array1 = np.array([1, 2, 3, 4, 5])
print("Array1:", array1)

# Criando arrays bidimensionais (matrizes)
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array2:\n", array2)

# Arrays de zeros e uns
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

ones = np.ones((2, 3))
print("Ones:\n", ones)

# Arrays com valores aleatórios
randoms = np.random.rand(3, 3)
print("Randoms:\n", randoms)


Array1: [1 2 3 4 5]
Array2:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Randoms:
 [[0.53831204 0.69450692 0.66000567]
 [0.31587837 0.65253228 0.95309891]
 [0.16564375 0.1458831  0.84328497]]


### 2.2 Operações com Arrays
NumPy facilita a execução de operações matemáticas em arrays de forma elementar.

In [46]:
# Operações elementares
soma = array1 + 5
print("Soma com escalar:", soma)

produto = array1 * 2
print("Produto com escalar:", produto)

# Operações entre arrays
array3 = np.array([6, 7, 8, 9, 10])
soma_arrays = array1 + array3
print("Soma de arrays:", soma_arrays)

produto_arrays = array1 * array3
print("Produto de arrays:", produto_arrays)


Soma com escalar: [ 6  7  8  9 10]
Produto com escalar: [ 2  4  6  8 10]
Soma de arrays: [ 7  9 11 13 15]
Produto de arrays: [ 6 14 24 36 50]


2.3 Propriedades dos Arrays

In [47]:
# Formato e tamanho dos arrays
print("Formato do array1:", array1.shape)
print("Tamanho do array1:", array1.size)

print("Formato do array2:", array2.shape)
print("Tamanho do array2:", array2.size)


Formato do array1: (5,)
Tamanho do array1: 5
Formato do array2: (2, 3)
Tamanho do array2: 6


### 2.4 Funções Matemáticas
NumPy inclui uma variedade de funções matemáticas para operar em arrays.

In [48]:
# Funções matemáticas
print("Média do array1:", np.mean(array1))
print("Desvio padrão do array1:", np.std(array1))
print("Soma dos elementos do array1:", np.sum(array1))
print("Produto dos elementos do array1:", np.prod(array1))

# Funções trigonometricas
angulos = np.array([0, np.pi/2, np.pi])
senos = np.sin(angulos)
print("Senos dos ângulos:", senos)

# Exponencial e logaritmo
exp = np.exp(array1)
print("Exponencial:", exp)

log = np.log(array1)
print("Logaritmo:", log)


Média do array1: 3.0
Desvio padrão do array1: 1.4142135623730951
Soma dos elementos do array1: 15
Produto dos elementos do array1: 120
Senos dos ângulos: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logaritmo: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


### 2.5 Indexação e Fatiamento

Arrays NumPy podem ser indexados e fatiados de forma similar às listas.

In [49]:
# Indexação
print("Primeiro elemento do array1:", array1[0])
print("Último elemento do array1:", array1[-1])

# Fatiamento
print("Elementos do array1 do índice 1 ao 3:", array1[1:4])

# Fatiamento de arrays bidimensionais
print("Primeira linha do array2:\n", array2[0, :])
print("Segunda coluna do array2:\n", array2[:, 1])


Primeiro elemento do array1: 1
Último elemento do array1: 5
Elementos do array1 do índice 1 ao 3: [2 3 4]
Primeira linha do array2:
 [1 2 3]
Segunda coluna do array2:
 [2 5]


### 2.6 Alterando a Forma dos Arrays
NumPy permite alterar a forma dos arrays sem alterar os dados.

In [50]:
# Redimensionando arrays
array_reshaped = array2.reshape((3, 2))
print("Array2 reshaped para (3, 2):\n", array_reshaped)

# Flatten
array_flat = array2.flatten()
print("Array2 flatten:\n", array_flat)


Array2 reshaped para (3, 2):
 [[1 2]
 [3 4]
 [5 6]]
Array2 flatten:
 [1 2 3 4 5 6]


## Desafio de Implementação de Uso de NumPy

Neste desafio, você usará a biblioteca NumPy para realizar operações matemáticas e manipulações de arrays. Você precisa completar as tarefas abaixo usando NumPy.

## Tarefas

1. **Criar Arrays**
    - Crie um array unidimensional (`array1`) contendo os números de 0 a 9.
    - Crie um array bidimensional (`array2`) de tamanho 3x3 contendo números aleatórios entre 0 e 1.

2. **Operações Matemáticas**
    - Calcule a soma de todos os elementos de `array1`.
    - Calcule a média dos elementos de `array2`.
    - Calcule a matriz transposta de `array2`.

3. **Manipulação de Arrays**
    - Redimensione `array1` para um array bidimensional de tamanho 2x5 (`array1_reshaped`).
    - Extraia a segunda coluna de `array2`.

4. **Operações Avançadas**
    - Crie uma máscara booleana para `array1` onde os valores são maiores que 5.
    - Use a máscara para filtrar os elementos de `array1` que são maiores que 5.
    - Calcule o produto dot (produto escalar) de `array1_reshaped` com sua transposta.

### Instruções

Preencha o código abaixo para completar cada tarefa. Use as funções e métodos do NumPy para realizar as operações necessárias.

In [ ]:
import numpy as np


# 1. Criar Arrays
# Crie um array unidimensional contendo os números de 0 a 9
array1 = np.arange(0,10)
print(f"O array1 é {array1}.")

# Crie um array bidimensional de tamanho 3x3 contendo números aleatórios entre 0 e 1
array2 = np.random.rand(3,3)
print(f"\nO array2 é \n{array2}")

# 2. Operações Matemáticas
# Calcule a soma de todos os elementos de array1
print(f"\nA somo dos elementos de array1 é {sum(array1)}.")

# Calcule a média dos elementos de array2
print(f"\nA média dos elementos do array2 é {round(np.mean(array2), 5)}")

# Calcule a matriz transposta de array2
print(f"\nA matriz transposta de array2 é \n{array2.T}")

# 3. Manipulação de Arrays
# Redimensione array1 para um array bidimensional de tamanho 2x5
array1_reshaped = array1.reshape(2,5)
print(f"\nO redimensionamento do array1 para 2x5 é \n{array1_reshaped}")

# Extraia a segunda coluna de array2
print(f"\nA segunda coluna do array2 é \n{array2[:,1]}")

# 4. Operações Avançadas
# Crie uma máscara booleana para array1 onde os valores são maiores que 5
array1_mask = array1 > 5
print(f"\nA máscara booleana do array1 onde os valores são maiores que 5 é {array1_mask}.")

# Use a máscara para filtrar os elementos de array1 que são maiores que 5
print(f"\nOs valores do array1 maiores do que 5 são {array1[array1_mask]}.")

# Calcule o produto dot (produto escalar) de array1_reshaped com sua transposta
array_dot = array1_reshaped @ array1_reshaped.T
print(f"\nO produto de array1_reshaped com sua transposta é \n{array_dot}")


O array1 é [0 1 2 3 4 5 6 7 8 9].

O array2 é 
[[0.33885064 0.39398569 0.83991602]
 [0.16752471 0.80961985 0.16944737]
 [0.94677409 0.42456358 0.91050378]].

A somo dos elementos de array1 é 45.

A média dos elementos do array2 é 0.55569

A matriz transposta de array2 é 
[[0.33885064 0.16752471 0.94677409]
 [0.39398569 0.80961985 0.42456358]
 [0.83991602 0.16944737 0.91050378]]

O redimensionamento do array1 para 2x5 é 
[[0 1 2 3 4]
 [5 6 7 8 9]]

A segunda coluna do array2 é 
[0.39398569 0.80961985 0.42456358]

A máscara booleana do array1 onde os valores são maiores que 5 é [False False False False False False  True  True  True  True].

Os valores do array1 maiores do que 5 são [6 7 8 9].

O produto de array1_reshaped com sua transposta é 
[[ 30  80]
 [ 80 255]].


<a name="section3"></a>
## 3. Pandas: Manipulação de Dados

Pandas é uma biblioteca poderosa para análise e manipulação de dados. Ela fornece estruturas de dados flexíveis, como DataFrames, que facilitam o trabalho com dados estruturados

### 3.1 Criando DataFrames

In [52]:
import pandas as pd

In [53]:
# Criando um DataFrame
data = {'Nome': ['Ana', 'João', 'Maria'],
        'Idade': [23, 34, 29],
        'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']}
df = pd.DataFrame(data)
print(df)


    Nome  Idade          Cidade
0    Ana     23       São Paulo
1   João     34  Rio de Janeiro
2  Maria     29  Belo Horizonte


### 3.2 Operações com DataFrames

In [54]:
# Selecionando colunas
print("Idades:", df['Idade'])

# Filtrando linhas
print("Pessoas com idade maior que 25:", df[df['Idade'] > 25])

# Estatísticas descritivas
print("Estatísticas:", df.describe())


Idades: 0    23
1    34
2    29
Name: Idade, dtype: int64
Pessoas com idade maior que 25:     Nome  Idade          Cidade
1   João     34  Rio de Janeiro
2  Maria     29  Belo Horizonte
Estatísticas:            Idade
count   3.000000
mean   28.666667
std     5.507571
min    23.000000
25%    26.000000
50%    29.000000
75%    31.500000
max    34.000000


## Desafio 2: Uso de Pandas
**Problema**

Você recebeu um arquivo CSV contendo informações sobre as vendas de uma loja. Sua tarefa é usar a biblioteca Pandas para realizar algumas análises e operações nos dados.

Requisitos

1. **Carregar o arquivo CSV:**

O arquivo se chama vendas.csv e contém as colunas: Data, Produto, Vendas, Custo.

2. **Análises e Operações**:

Carregar os dados do CSV em um DataFrame.
Exibir as 5 primeiras linhas do DataFrame.
Calcular o lucro para cada venda (Lucro = Vendas - Custo) e adicionar uma nova coluna Lucro ao DataFrame.
Calcular o total de vendas e o total de lucro por produto.
Filtrar e exibir apenas as vendas que tiveram lucro maior que 50.
Criar um gráfico de barras mostrando o total de vendas por produto.

```python
Output exemplo

Data,Produto,Vendas,Custo

2024-01-01,Produto A,100,70
2024-01-02,Produto B,150,90
2024-01-03,Produto A,200,100
2024-01-04,Produto C,50,30
2024-01-05,Produto B,120,60
```

Link para baixar o [arquivo CSV de vendas](https://drive.google.com/file/d/1K8gtX2kQgBy8dTMpte-HKXuqFNRMgtU8/view?usp=sharing)






---


Passo a Passo para Gerar Relatórios em Pandas
#### 1. Importar a Biblioteca Pandas
Primeiro, precisamos importar a biblioteca Pandas. Se você estiver usando o Google Colab, ela já vem pré-instalada.



In [55]:
import pandas as pd

2. Carregar os Dados
Vamos supor que temos um arquivo CSV chamado vendas.csv com as seguintes colunas: Data, Produto, Vendas, Custo.

In [56]:
# Carregar os dados do CSV
df = pd.read_csv('vendas.csv')


FileNotFoundError: [Errno 2] No such file or directory: 'vendas.csv'

#### 3. Exibir as Primeiras Linhas do DataFrame
Após carregar os dados, é uma boa prática visualizar as primeiras linhas para entender a estrutura do DataFrame.

In [ ]:
print(df.head())


#### 4. Entender a Estrutura dos Dados
Para entender melhor a estrutura dos dados, você pode usar os métodos info() e describe().

In [ ]:
print(df.info())
print(df.describe())


#### 5. Manipular os Dados
Agora vamos fazer algumas manipulações comuns, como adicionar colunas, filtrar dados, agrupar dados, etc.

**Adicionar Coluna de Lucro**

Vamos adicionar uma coluna de lucro, que é a diferença entre Vendas e Custo.

In [ ]:
df['Lucro'] = df['Vendas'] - df['Custo']
print(df.head())


**Filtrar Dados**

Vamos filtrar as vendas que tiveram lucro maior que 50.

In [ ]:
lucro_maior_50 = df[df['Lucro'] > 50]
print(lucro_maior_50)


**Agrupar Dados**

Vamos calcular o total de vendas e lucro por produto.

In [ ]:
relatorio_produtos = df.groupby('Produto')[['Vendas', 'Lucro']].sum()
print(relatorio_produtos)


#### 6. Gerar Relatórios
Com os dados manipulados, podemos criar relatórios. Vamos gerar um relatório simples de vendas totais por produto e salvar como um novo CSV.

**Relatório de Vendas por Produto**

In [ ]:
relatorio_vendas = df.groupby('Produto')['Vendas'].sum().reset_index()
relatorio_vendas.columns = ['Produto', 'Total de Vendas']
print(relatorio_vendas)

# Salvar o relatório em um novo arquivo CSV
relatorio_vendas.to_csv('relatorio_vendas_por_produto.csv', index=False)


#### 7. Relatórios com Estatísticas
Podemos calcular algumas estatísticas básicas e adicionar ao relatório.

In [ ]:
estatisticas_vendas = df.describe()[['Vendas', 'Lucro']]
print(estatisticas_vendas)

# Salvar as estatísticas em um novo arquivo CSV
estatisticas_vendas.to_csv('estatisticas_vendas.csv')


<a name="section4"></a>

## 4. Matplotlib: Visualização de Dados

Matplotlib é uma biblioteca usada para criar visualizações estáticas, animadas e interativas em Python.

### 4.1 Criando um Gráfico Simples

In [ ]:
import matplotlib.pyplot as plt

1. Plotar os dados do relatório de Vendas por Produto da Seção 3 Pandas

In [ ]:
# Gráfico de barras para total de vendas por produto
plt.figure(figsize=(10, 6))
plt.bar(relatorio_vendas['Produto'], relatorio_vendas['Total de Vendas'], color='skyblue')
plt.xlabel('Produto')
plt.ylabel('Total de Vendas')
plt.title('Total de Vendas por Produto')
plt.show()


2. Gráfico de Linha
Um gráfico de linha é útil para mostrar tendências ao longo do tempo ou alguma sequência contínua de dados.

In [ ]:
# Dados de exemplo
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

# Criar o gráfico de linha
plt.figure(figsize=(8, 5))
plt.plot(x, y, marker='o', linestyle='-', color='b', label='Série 1')
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')
plt.title('Gráfico de Linha Simples')
plt.legend()
plt.grid(True)
plt.show()


3. Gráfico de Barras
Um gráfico de barras é útil para comparar diferentes categorias ou grupos de dados.

In [ ]:
# Dados de exemplo
categorias = ['A', 'B', 'C', 'D']
valores = [5, 7, 3, 8]

# Criar o gráfico de barras
plt.figure(figsize=(8, 5))
plt.bar(categorias, valores, color='skyblue')
plt.xlabel('Categorias')
plt.ylabel('Valores')
plt.title('Gráfico de Barras Simples')
plt.show()


4. Gráfico de Dispersão (Scatter Plot)
Um gráfico de dispersão é útil para visualizar a relação entre duas variáveis.

In [ ]:
# Dados de exemplo
x = [5, 7, 8, 7, 2, 17, 2, 9, 4, 11]
y = [99, 86, 87, 88, 100, 86, 103, 87, 94, 78]

# Criar o gráfico de dispersão
plt.figure(figsize=(8, 5))
plt.scatter(x, y, color='red', label='Dados de Dispersão')
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')
plt.title('Gráfico de Dispersão Simples')
plt.legend()
plt.show()


<a name="section5"></a>

## 5. Scikit-learn: Introdução ao Machine Learning
Por enquanto usaremos modelos já existentes.

Scikit-learn é uma biblioteca para aprendizado de máquina em Python. Ela fornece ferramentas simples e eficientes para análise de dados e modelagem preditiva.

### 5.1 Exemplo de Regressão Linear

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [ ]:
# Dados de exemplo
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 3, 5, 7, 11])

# Criando o modelo
model = LinearRegression()
model.fit(X, y)

# Fazendo previsões
y_pred = model.predict(X)
print("Previsões:", y_pred)

# Visualizando a regressão
plt.scatter(X, y, color='black')
plt.plot(X, y_pred, color='blue', linewidth=3)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Regressão Linear')
plt.show()


Este notebook é uma introdução básica para começar com Python em Data Science. Pratique com seus próprios conjuntos de dados e explore mais funções das bibliotecas mencionadas para se aprofundar na análise de dados.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Passo 2: Criar um Conjunto de Dados Fictício

In [ ]:
# Gerar dados fictícios
np.random.seed(42)
num_samples = 100 #numero de amostras

area = np.random.normal(1500, 300, num_samples)
quartos = np.random.randint(1, 6, num_samples)
idade = np.random.randint(0, 30, num_samples)
preco = 50000 + (area * 50) + (quartos * 3000) - (idade * 100) + np.random.normal(0, 10000, num_samples)

# Criar DataFrame
df = pd.DataFrame({'Area': area, 'Quartos': quartos, 'Idade': idade, 'Preco': preco})
print(df.head())


Passo 3: Visualizar os Dados

In [ ]:
# Visualizar a relação entre 'Area' e 'Preco'
plt.scatter(df['Area'], df['Preco'])
plt.xlabel('Área (sq ft)')
plt.ylabel('Preço ($)')
plt.title('Área vs Preço')
plt.show()


Passo 4: Dividir os Dados em Conjuntos de Treinamento e Teste

In [ ]:
# Dividir os dados em conjuntos de treinamento e teste
X = df[['Area', 'Quartos', 'Idade']]
y = df['Preco']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Passo 5: Treinar o Modelo de Regressão Linear

In [ ]:
# Criar o modelo de regressão linear
model = LinearRegression()

# Treinar o modelo
model.fit(X_train, y_train)


Passo 6: Fazer Previsões

In [ ]:
# Fazer previsões no conjunto de teste
y_pred = model.predict(X_test)


Passo 7: Avaliar o Modelo

In [ ]:
# Avaliar o modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')


Passo 8: Visualizar as Previsões

In [ ]:
# Comparar os valores reais e previstos
plt.scatter(y_test, y_pred)
plt.xlabel('Valores Reais')
plt.ylabel('Valores Previstos')
plt.title('Valores Reais vs Valores Previstos')
plt.show()


<a name="section6"></a>

## Extra (Opcional)

#### **Desafio de Regressão Linear**

Agora que você viu um exemplo de como realizar uma regressão linear, aqui está um desafio para você praticar:

**Desafio
Dataset**: Utilize um conjunto de dados real do [Kaggle](https://www.kaggle.com/datasets?fileType=csv) ou qualquer outro repositório. Um exemplo pode ser o dataset "Boston Housing" ou qualquer outro dataset de preços de casas.

**Objetivo**: Crie um modelo de regressão linear para prever o preço das casas com base nas características disponíveis no dataset.


**Passos a seguir**:
Carregue e explore os dados.
Faça a limpeza e o pré-processamento dos dados (trate valores ausentes, se necessário).
Divida os dados em conjuntos de treinamento e teste.
Treine um modelo de regressão linear.
Avalie o modelo usando métricas como MSE e R^2.
Visualize os resultados com gráficos apropriados.

Mais extras:
Experimente normalizar ou padronizar os dados antes de treinar o modelo.
Tente usar a técnica de feature selection para selecionar as características mais importantes.

### IEEE CS & CIS UFPB

Linkedin: https://www.linkedin.com/company/ieee-cs-cis-chapter-at-ufpb/?originalSubdomain=br

GitHub Page: https://github.com/CS-CIS-Joint-UFPB

Linketree  https://linktr.ee/cs.ufpb